In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [9]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [10]:
df['sex'] = df['sex'].map({
    'male' : 0,
    'female' : 1
})
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [12]:
df.rename(columns={'sex':"isFemale"},inplace=True)
df.head()

,survived,pclass,isFemale,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,1,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,0,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [65]:
df = df.drop(columns= ['who','deck','alive'],axis=1)
df.head()

,survived,pclass,isFemale,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alone
0,0,0.827377,0,-0.580044,0.432793,-0.473674,-0.502445,0.581114,0.827377,1,0.581114,0
1,1,-1.566107,1,0.650112,0.432793,-0.473674,0.786845,-1.938460,-1.566107,0,-1.938460,0
2,1,0.827377,1,-0.272505,-0.474545,-0.473674,-0.488854,0.581114,0.827377,0,0.581114,1
3,1,-1.566107,1,0.419458,0.432793,-0.473674,0.420730,0.581114,-1.566107,0,0.581114,0
4,0,0.827377,0,0.419458,-0.474545,-0.473674,-0.486337,0.581114,0.827377,1,0.581114,1

In [22]:
from sklearn.preprocessing import LabelEncoder

In [24]:
lb = LabelEncoder()

In [30]:
df['embarked'] = lb.fit_transform(df['embarked'])
df['class'] = lb.fit_transform(df['class'])
df['embark_town'] = lb.fit_transform(df['embark_town'])
df.head()

,survived,pclass,isFemale,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alive,alone
0,0,3,0,22.0,1,0,7.2500,2,2,True,2,no,False
1,1,1,1,38.0,1,0,71.2833,0,0,False,0,yes,False
2,1,3,1,26.0,0,0,7.9250,2,2,False,2,yes,True
3,1,1,1,35.0,1,0,53.1000,2,0,False,2,yes,False
4,0,3,0,35.0,0,0,8.0500,2,2,True,2,no,True

In [40]:
# df['age'].isnull().sum()
df['age'] = df['age'].fillna(df['age'].mean())

In [41]:
df['age'].isnull().sum()

np.int64(0)

In [42]:
df['age'] = df['age'].astype(int)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   isFemale     891 non-null    int64
 3   age          891 non-null    int64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    int64
 8   class        891 non-null    int64
 9   adult_male   891 non-null    int64
 10  embark_town  891 non-null    int64
 11  alive        891 non-null    object
 12  alone        891 non-null    int64
dtypes: float64(1), int64(11), object(1)
memory usage: 90.6+ KB

In [45]:
df['adult_male'] = df['adult_male'].astype(int)
df['alone'] = df['alone'].astype(int)
df.head()

,survived,pclass,isFemale,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alive,alone
0,0,3,0,22,1,0,7.2500,2,2,1,2,no,0
1,1,1,1,38,1,0,71.2833,0,0,0,0,yes,0
2,1,3,1,26,0,0,7.9250,2,2,0,2,yes,1
3,1,1,1,35,1,0,53.1000,2,0,0,2,yes,0
4,0,3,0,35,0,0,8.0500,2,2,1,2,no,1

In [47]:
cleaned_df = df.copy()

In [48]:
df.columns

Index(['survived', 'pclass', 'isFemale', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'adult_male', 'embark_town', 'alive', 'alone'],
      dtype='object')

In [56]:
cols = [ 'pclass', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class',  'embark_town']

In [60]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df[cols] = scaler.fit_transform(df[cols])
df

,survived,pclass,isFemale,age,sibsp,parch,fare,embarked,class,adult_male,embark_town,alive,alone
0,0,0.827377,0,-0.580044,0.432793,-0.473674,-0.502445,0.581114,0.827377,1,0.581114,no,0
1,1,-1.566107,1,0.650112,0.432793,-0.473674,0.786845,-1.938460,-1.566107,0,-1.938460,yes,0
2,1,0.827377,1,-0.272505,-0.474545,-0.473674,-0.488854,0.581114,0.827377,0,0.581114,yes,1
3,1,-1.566107,1,0.419458,0.432793,-0.473674,0.420730,0.581114,-1.566107,0,0.581114,yes,0
4,0,0.827377,0,0.419458,-0.474545,-0.473674,-0.486337,0.581114,0.827377,1,0.581114,no,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,-0.369365,0,-0.195620,-0.474545,-0.473674,-0.386671,0.581114,-0.369365,1,0.581114,no,1
887,1,-1.566107,1,-0.810699,-0.474545,-0.473674,-0.044381,0.581114,-1.566107,0,0.581114,yes,1
888,0,0.827377,1,-0.041851,0.432793,2.008933,-0.176263,0.581114,0.827377,0,0.581114,no,0
889,1,-1.566107,0,-0.272505,-0.474545,-0.473674,-0.044381,-1.938460,-1.566107,1,-1.938460,yes,1
890,0,0.827377,0,0.188804,-0.474545,-0.473674,-0.492378,-0.678673,0.827377,1,-0.678673,no,1

In [72]:
X = df.drop(columns=['survived'])
Y = df['survived']

In [73]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,train_size=0.20,random_state=45)

In [83]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)

model.fit(X_train,Y_train)

KNeighborsClassifier()

In [84]:
Y_pred = model.predict(X_test)
Y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0])

In [85]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [86]:
accuracy_score(Y_test,Y_pred)

0.7938288920056101

In [88]:
confusion_matrix(Y_test,Y_pred)

array([[375,  67],
       [ 80, 191]])

In [89]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.82      0.85      0.84       442
           1       0.74      0.70      0.72       271

    accuracy                           0.79       713
   macro avg       0.78      0.78      0.78       713
weighted avg       0.79      0.79      0.79       713