In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [15]:
df = pd.read_csv("heart_disease.csv")
df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [34]:
print(df.columns)
print(df.shape)
print(df.info())

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='object')
(9632, 21)
<class 'pandas.core.frame.DataFrame'>
Index: 9632 entries, 1 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9632 non-null   float64
 1   Gender                9632 non-null   object
 2   Blood Pressure        9632 non-null   float64
 3   Cholesterol Level     9632 non-null   float64
 4   Exercise Habits       9632 non-null   object
 5   Smoking               9632 non-null   object
 6   Family Heart Disease  9632 non-null   object
 7   Diabetes              9632 non-null   object
 8   BMI                   9632 non-null   float64
 9   High Blood Pressure   9632 non-null   object
 10  Low HDL Cholesterol   9632 non-null   object
 11  High LDL Cholesterol  9632 non-null   object
 12  Alcohol Consumption   7143 non-null   object
 13  Stress Level          9632 non-null   object
 14  Sleep Hours           9632 non-null   float64
 15  Sugar Consumption     9632 non-null   object
 16  Triglyceride Level    9632 non-null   float64
 17  Fasting Blood Sugar   9632 non-null   float64
 18  CRP Level             9632 non-null   float64
 19  Homocysteine Level    9632 non-null   float64
 20  Heart Disease Status  9632 non-null   object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB
None

In [39]:
df.isnull().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

In [28]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Blood Pressure'] = df['Blood Pressure'].fillna(df['Blood Pressure'].mean())
df['Cholesterol Level'] = df['Cholesterol Level'].fillna(df['Cholesterol Level'].mean())
df['BMI'] = df['BMI'].fillna(df['BMI'].mean())

In [32]:

df = df.dropna(subset=['Gender'])
df = df.dropna(subset=['Exercise Habits'])
df = df.dropna(subset=['Smoking'])
df = df.dropna(subset=['Family Heart Disease'])
df = df.dropna(subset=['Diabetes'])
df = df.dropna(subset=['High Blood Pressure'])
df = df.dropna(subset=['Low HDL Cholesterol'])
df = df.dropna(subset=['High LDL Cholesterol'])
df = df.dropna(subset=['Stress Level'])
df = df.dropna(subset=['Sleep Hours'])
df = df.dropna(subset=['Sugar Consumption'])
df = df.dropna(subset=['Triglyceride Level'])
df = df.dropna(subset=['Fasting Blood Sugar'])
df = df.dropna(subset=['CRP Level'])
df = df.dropna(subset=['Homocysteine Level'])

In [38]:
df = df.fillna(df['Alcohol Consumption'].mode()[0])

In [40]:
df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
5,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,...,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No

In [47]:
from sklearn.preprocessing import LabelEncoder

lb = LabelEncoder()

cols = [ 'Gender','Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes',
        'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level',
       'Sugar Consumption', 'Heart Disease Status']

for col in cols:
  df[col] = lb.fit_transform(df[col])

df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,69.0,0,146.0,286.0,0,0,1,1,25.221799,0,...,0,2,0,8.744034,2,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,1,0,0,0,29.855447,0,...,1,1,1,4.440440,1,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,0,1,1,0,24.130477,1,...,1,1,0,5.249405,0,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,1,1,1,1,20.486289,1,...,0,1,0,7.030971,0,263.0,154.0,10.381259,8.153887,0
5,25.0,1,152.0,257.0,1,1,0,0,28.144681,0,...,0,1,2,5.504876,1,126.0,91.0,4.297575,10.815983,0

In [52]:
Cleaned_df = df.copy()

In [53]:
# Standerd Scaler

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

for col in df.drop('Heart Disease Status',axis=1):
  Cleaned_df[col] = scaler.fit_transform(df[[col]])
Cleaned_df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
1,1.081053,-0.999377,-0.216161,1.393849,-1.214484,-1.027368,1.004787,1.010227,-0.609706,-1.003953,...,-0.987618,0.88955,-1.238177,1.000716,1.241413,-1.348371,1.561600,0.433499,1.584686,0
2,-0.184813,1.000623,-1.355065,-0.213129,0.005192,-1.027368,-0.995236,-0.989877,0.126995,-1.003953,...,1.012537,-0.32321,-0.013855,-1.453666,0.009845,1.635836,-1.190686,1.205988,-0.283547,0
3,-0.955339,-0.999377,-1.582845,1.554547,-1.214484,0.973361,1.004787,-0.989877,-0.783215,0.996063,...,1.012537,-0.32321,-1.238177,-0.992306,-1.221722,0.488064,-1.106001,1.159741,-1.503641,0
4,0.585714,1.000623,0.922743,0.383749,0.005192,0.973361,1.004787,1.010227,-1.362603,0.996063,...,-0.987618,-0.32321,-1.238177,0.023739,-1.221722,0.143732,1.434571,0.669742,-0.996073,0
5,-1.340602,1.000623,0.125510,0.728101,0.005192,0.973361,-0.995236,-0.989877,-0.144999,-1.003953,...,-0.987618,-0.32321,1.210467,-0.846608,0.009845,-1.428715,-1.233029,-0.731242,-0.379632,0

In [59]:
X = Cleaned_df.drop("Heart Disease Status",axis=1)
Y = Cleaned_df['Heart Disease Status']

In [60]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=45)

In [75]:
# MODELS

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

# TEST

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score,recall_score

In [95]:
models = {
    "Logistic Regression " : LogisticRegression(),
    "KNN" : KNeighborsClassifier(),
    "Dicision Tree" : DecisionTreeClassifier(),
    "Naive Bayes" : GaussianNB(),
    "SVM" : SVC()
}

In [96]:


for name, model in models.items():
    model.fit(X_train,Y_train)
    Y_pred = model.predict(X_test)

    acc = accuracy_score(Y_test,Y_pred)
    recall = recall_score(Y_test,Y_pred)
    f1Score = f1_score(Y_test,Y_pred)
    classificationReport = classification_report(Y_test,Y_pred)

    print(f'------------------{name}------------------------')
    print(f'Accuracy -----------> {acc}')
    print(classificationReport)

------------------Logistic Regression ------------------------
Accuracy -----------> 0.8033212247016087
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1548
           1       0.00      0.00      0.00       379

    accuracy                           0.80      1927
   macro avg       0.40      0.50      0.45      1927
weighted avg       0.65      0.80      0.72      1927

------------------KNN------------------------
Accuracy -----------> 0.7716658017644006
              precision    recall  f1-score   support

           0       0.80      0.95      0.87      1548
           1       0.16      0.04      0.06       379

    accuracy                           0.77      1927
   macro avg       0.48      0.49      0.46      1927
weighted avg       0.67      0.77      0.71      1927

------------------Dicision Tree------------------------
Accuracy -----------> 0.6683964711987546
              precision    recall  f1-score   support

           0       0.81      0.77      0.79      1548
           1       0.20      0.24      0.22       379

    accuracy                           0.67      1927
   macro avg       0.51      0.51      0.50      1927
weighted avg       0.69      0.67      0.68      1927

------------------Naive Bayes------------------------
Accuracy -----------> 0.8033212247016087
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1548
           1       0.00      0.00      0.00       379

    accuracy                           0.80      1927
   macro avg       0.40      0.50      0.45      1927
weighted avg       0.65      0.80      0.72      1927

------------------SVM------------------------
Accuracy -----------> 0.8033212247016087
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1548
           1       0.00      0.00      0.00       379

    accuracy                           0.80      1927
   macro avg       0.40      0.50      0.45      1927
weighted avg       0.65      0.80      0.72      1927